### ISSUE TITLE
Installing PyQuran on Windows

### ISSUE THREAD

**Issue by OmarMerghany** [hci-lab/PyQuran#1]
I have tried to install pyquran on Windows 10 using Python 3, but I have encountered an error regarding decoding as attached in the image.
After searching this error it turns out that the default system codec on Windows is different than unix (utf-8)
(the error coming from cp1252.py).
Thus, I have replaced the "open()" calls  which is in setup file (setup.py) with:
`with open('README.md', encoding="utf-8") as f:
     long_description = f.read()`
and run 

> python setup.py install 

and it worked fine with me

![bug01](https://user-images.githubusercontent.com/13571281/42739099-89096302-8890-11e8-927f-baf9dfd3ded8.PNG)

**Comment by TahaMagdy** [comment]
- But you should've used `pip3` not `pip`, see the [Installation section](https://github.com/hci-lab/PyQuran#install). Does the same problem happen when you `$ pip3 install pyquran`?
- `Python3` handles the unicode encoding differently to `Python2`. We support `Python3` only.

**Comment by OmarMerghany** [comment]
* I have tried both `pip` and `pip3` and they gave me the same error.
* It's related to the default system codec on Windows
![bug02](https://user-images.githubusercontent.com/13571281/42751236-6e022c10-88ea-11e8-90ee-37ce2153033d.PNG)

**Comment by TahaMagdy** [comment]
YES, I'll change the `setup.py` to:
```python
with open('README.md', encoding="utf-8") as f:
     long_description = f.read()
```
Could you try now? Make sure that the `pip3` installs `pyquran 1.0.1`.

**Comment by OmarMerghany** [comment]
It works now using this command `pip3 install pyquran`
