### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by OscarTango1995** [hci-lab/PyQuran#2]
Hi another feature would be great such that if the user makes a mistake while typing any Verse/Ayah the system tells him the correct version of that Verse/Ayah and also highlight his mistakes.

For Example
User:ملكيوم الدين
System: ملك يوم الدين
Error:ك

**Comment by TahaMagdy** [comment]
Interesting, we will take that in mind, so thank you very much.
However,  you can contribute to PyQuran by implementing this feature if you wish. Read [this](https://hci-lab.github.io/PyQuran-Private/CONTRIBUTING/) for more details, we need contributors.
