### ISSUE TITLE
short alef  error

### ISSUE THREAD

**Issue by akbar9000** [hci-lab/PyQuran#3]
عَلِمُ الْغَيْبِ وَالشَّهَدَةِ

it seems short alef is not working right
عالم الغیب و الشهادة

**Comment by TahaMagdy** [comment]
Thank you for using PyQuran.

In Mus'haf, it is written الشهدة without the alef letter. Like الرحمن ,السموت and a lot of other words. Quran text spellings (Othmani Rasm) are slightly different than what we use.

We get our Quran corpus from this standard: [Tanzil](http://tanzil.net/docs/home).

**Comment by akbar9000** [comment]
well compare your link with your program
'إِنَّا أَعْطَيْنَكَ الْكَوْثَرَ'  .. this is python output and 
this is the correct text in the link
إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ ﴿١﴾
there is no alef in your output..it is really wrong

عَالِمُ الْغَيْبِ وَالشَّهَادَةِ ۚ وَهُوَ الْحَكِيمُ الْخَبِيرُ ﴿٧٣﴾  
this the text in 
http://tanzil.net/#6:73

**Comment by TahaMagdy** [comment]
Becuase you chose the "Simple" text version not the "Uthmani" one.
Choose the "Uthmani".

The are different corpora, we use the "Uthmani", which is used also in Mus'haf.

<img width="251" alt="Screen Shot 2020-06-14 at 1 30 46 PM" src="https://user-images.githubusercontent.com/18517169/84592064-08afc400-ae43-11ea-83d7-f91711882ccb.png">
