### ISSUE TITLE
Requesting a version of the Arabic Poem Comprehensive Dataset (PCD)

### ISSUE THREAD

**Issue by Gheith-Abandah** [hci-lab/PyQuran#4]
I have read with interest the paper titled: Learning meters of Arabic and English poems with Recurrent Neural Networks. I am interested in processing Arabic poem using machine learning techniques. I have downloaded your Arabic Poem PCD Dataset and found it very useful. Thank you for providing this dataset to interested researchers. I am using the APCD version which link is in the following page: [https://hci-lab.github.io/ArabicPoetry-1-Private/](https://hci-lab.github.io/ArabicPoetry-1-Private/)

I have noticed that this dataset has the poem verses pre-processed as follows:

- The shaddah diacritic is converted to two letters
- The tanween diacritic is converted to haraka and noon

I am interested in performing some experiments on the original dataset before applying these two pre-processing changes. I appreciate if you share with us an original version of this dataset.

**Comment by TahaMagdy** [comment]
Check [it](https://hci-lab.github.io/ArabicPoetry-1-Private) out now.

**Comment by Gheith-Abandah** [comment]
Thank you for the update.
