### ISSUE TITLE
SyntaxWarning

### ISSUE THREAD

**Issue by MKM12345** [hci-lab/PyQuran#5]
Assalamualaykum, I was testing [this](https://github.com/hci-lab/PyQuran/blob/release/core/pyquran.py) file when I got this error:

```
python
main.py:536: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if((sentance[index] in (alphabet or alefat or hamzat)or sentance[index] is ' ' )):

```

Evidence:
![image](https://github.com/hci-lab/PyQuran/assets/120132998/15a7091f-3a5d-444d-8d2a-6d589f2875c1)

I am running Windows as my operating system and Python version 3.11.3 (the latest version today).

To reproduce the bug, you can use the following code:
```

sentance = "This is a test."
alphabet = "abcdefghijklmnopqrstuvwxyz"
alefat = "ءآأؤإئابتثجحخدذرزسشصضطظعغفقكلمنهوي"
hamzat = "ءآأؤإئ"
for index in range(len(sentance)):
    if((sentance[index] in (alphabet or alefat or hamzat)or sentance[index] is ' ' )):
        pass

```

So am I missing something here?

**Comment by TahaMagdy** [comment]
WaalikomElsalam, You're not missing anything :)
it should be `==` not `is`. Make a pull request with the fix please.

**Comment by MKM12345** [comment]
Ok jazakallah. Will do.
